[workspace]
    members = [
        "fiv-date-macro", "fiv-date-core",
    ]

[package]
name = "fiv-date"
version = "0.3.0"
edition = "2021"

[dependencies]
fiv-date-macro={path=".\\fiv-date-macro"}
fiv-date-core={path=".\\fiv-date-core"}