[package]
name = "date_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
fiv-date={git="ssh://github.com/Fives-55555/fiv-date.git",rev = "2493dea292a763fc248454ac59ba4125c58cfaf6"}